# Kustomize overlay for the development environment
namespace: studio-app-dev
resources:
  - ../../base
patchesStrategicMerge:
  - app-configmap.yaml
  - flask-deployment.yaml
  - react-deployment.yaml
  - ingress.yaml