# Kustomize overlay for the production environment
namespace: studio-app-prod
resources:
  - ../../base
patchesStrategicMerge:
  - flask-deployment.yaml
  - react-deployment.yaml
  - postgres-deployment.yaml