# Service to expose the React frontend within the cluster
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: studio-app
spec:
  type: ClusterIP
  selector:
    app: react
  ports:
  - port: 80          # incoming port
    targetPort: 3000  # container port of the React app