# Stores database credentials (values are base64 encoded)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: studio-app
type: Opaque
data:
  POSTGRES_USER: "c3R1ZGlv"       # base64 for 'studio'
  POSTGRES_PASSWORD: "cGFzc3dvcmQ=" # base64 for 'password'