apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1      # one Grafana pod is enough
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: provisioning
              mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: dashboards
          configMap:
            name: grafana-dashboards      # contains JSON dashboards
            items:
              - key: sample-dashboard.json
                path: sample-dashboard.json
        - name: provisioning
          configMap:
            name: grafana-dashboards      # tells Grafana where to find dashboards
            items:
              - key: provider.yaml
                path: provider.yaml