# Dashboards and provisioning configuration for Grafana
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    app: grafana
    grafana_dashboard: "1"
data:
  # Configures how Grafana loads dashboards from files
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
  sample-dashboard.json: |
    {
      "annotations": {"list": []},
      "panels": [],
      "title": "Sample Dashboard",
      "version": 1
    }