apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-07-10T12:21:18Z"
  generation: 1
  labels:
    app: test-backend
  name: test-backend
  namespace: jenkins
  resourceVersion: "20974"
  uid: 68eb3f7e-4b77-4d5c-9c83-c7775ef313d0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-backend
    spec:
      containers:
      - image: avit83/backend:latest
        imagePullPolicy: Always
        name: backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-10T12:21:26Z"
    lastUpdateTime: "2025-07-10T12:21:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-10T12:21:18Z"
    lastUpdateTime: "2025-07-10T12:21:26Z"
    message: ReplicaSet "test-backend-64cd96457f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
