apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
  namespace: jenkins
  labels:
    app: test-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
      - name: backend
        image: avit83/backend:latest
        imagePullPolicy: Always